name: CI

on:
  release:
    types: [released]

env:
  JAVA_VERSION: 1.11

jobs:
  wsdl_test:
    name: SalesForce-Test Package Build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: WSDL Version
        run: |
          version=`cat wsdl.test.xml | grep "Salesforce.com Enterprise Web Services API Version" | awk '{ print $NF }'`
          echo "::set-output name=version::${version}.+"
        id: wsdl_version

      - name: Download Force WSC Jar
        run: |
          ./gradlew -b wsc-download.gradle download -Pversion=${{ steps.wsdl_version.outputs.version }}

      - name: Build Jar
        run: |
          java -Dpackage-prefix=wsc -classpath ".:jar/*" com.sforce.ws.tools.wsdlc wsdl.test.xml salesForceTest-${{ github.event.release.tag_name }}.jar

      - name: Publish Jar
        env:
          GITHUB_PACKAGE_USER_USERNAME: ${{ secrets.USER_GITHUB }}
          GITHUB_PACKAGE_USER_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          mvn -B --settings settings.xml deploy:deploy-file -DgroupId=com.pax8.sftrial -DartifactId=sales-force-test -Dversion=${{ github.event.release.tag_name }} -DgeneratePom=true -Dpackaging=jar -Dfile=salesForceTest-${{ github.event.release.tag_name }}.jar -DrepositoryId=github -Durl=https://maven.pkg.github.com/pax8/pax8
      
  wsdl_prod:
    name: SalesForce-Prod Package Build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: WSDL Version
        run: |
          version=`cat wsdl.prod.xml | grep "Salesforce.com Enterprise Web Services API Version" | awk '{ print $NF }'`
          echo "::set-output name=version::${version}.+"
        id: wsdl_version

      - name: Download Force WSC Jar
        run: |
          ./gradlew -b wsc-download.gradle download -Pversion=${{ steps.wsdl_version.outputs.version }}

      - name: Build Jar
        run: |
          java -Dpackage-prefix=wsc -classpath ".:jar/*" com.sforce.ws.tools.wsdlc wsdl.prod.xml salesForceProd-${{ github.event.release.tag_name }}.jar

      - name: Publish Jar
        env:
          GITHUB_PACKAGE_USER_USERNAME: ${{ secrets.USER_GITHUB }}
          GITHUB_PACKAGE_USER_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          mvn -B --settings settings.xml deploy:deploy-file -DgroupId=com.pax8.sftrial -DartifactId=sales-force-prod -Dversion=${{ github.event.release.tag_name }} -DgeneratePom=true -Dpackaging=jar -Dfile=salesForceProd-${{ github.event.release.tag_name }}.jar -DrepositoryId=github -Durl=https://maven.pkg.github.com/pax8/pax8
      

