name: Main to Master sync

on:
  push:
    branches:
      - 'main'

jobs:
  sync:
    name: main-to-master-sync
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: sync
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          git remote set-url --push origin https://foo:$GITHUB_TOKEN@github.com/spandianpax8/salesforce-wsdl
          git push origin master --force
        
